"use strict";
let normalx = 'hola';
normalx = 10;
normalx = true;
let usuario = 20;
console.log(normal);
let nombre = 'Juan';
nombre = 'Pedro';
//nombre = null;
console.log(nombre);
let value;
console.log(value);
value = true;
value = 10;
value = 'hola';
value = {};
value = [];
value = undefined;
value = null;
console.log(value);
let miValor;
console.log(miValor);
let value1 = miValor;
let value2 = miValor;
//let value3: boolean = miValor; //Error
const edad = 18;
console.log('Edad:', edad);
const sueldo = 20.2;
const total = Number('5678');
console.log('Sueldo:', sueldo);
console.log('Total:', total);
const personaje = "El Chavo";
const otroPersonaje = 'El Chapulin Colorado';
const otroMas = `El Dr. Chapatin`;
console.log('Personaje:', personaje);
const heroe = "Superman";
const identidad = `Clark Kent es ${heroe}`;
let vengador;
vengador = 'Ironman';
console.log(vengador.charAt(0));
vengador = 150.555;
console.log(vengador.toFixed(2));
